import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs/promises';
import pg from 'pg';
import { Wallet } from 'ethers';
import { buildApp } from '../apps/api/src/app.js';
import { createPgStore } from '../apps/api/src/store.js';
const dbUrl = process.env.API_TEST_DATABASE_URL;
test('PostgreSQL API: signed auth, replay, expiry, logout, owner isolation and unhealthy worker', { skip: !dbUrl }, async t => {
  const schema = 'api_test_' + crypto.randomBytes(8).toString('hex');
  const admin = new pg.Pool({ connectionString: dbUrl });
  await admin.query('CREATE SCHEMA "' + schema + '"');
  const pool = new pg.Pool({ connectionString: dbUrl, options: '-c search_path=' + schema });
  t.after(async () => { await pool.end(); await admin.query('DROP SCHEMA "' + schema + '" CASCADE'); await admin.end(); });
  await pool.query(await fs.readFile(new URL('../apps/api/migrations/001_core.sql', import.meta.url), 'utf8'));
  const store = createPgStore(dbUrl, { pool });
  const app = await buildApp({ store, chain: { ok: true } });
  t.after(() => app.close());
  const wallet = Wallet.createRandom();
  const c = (await app.inject({method:'POST',url:'/api/v1/auth/challenge',payload:{address:wallet.address,chainId:50312}})).json();
  const payload = { challengeId: c.challengeId, signature: await wallet.signMessage(c.message) };
  const results = await Promise.all(Array.from({length:6},()=>app.inject({method:'POST',url:'/api/v1/auth/verify',payload})));
  assert.equal(results.filter(r=>r.statusCode===200).length,1);
  assert.equal(results.filter(r=>r.statusCode===401).length,5);
  const cookie = results.find(r=>r.statusCode===200).headers['set-cookie'].split(';')[0];
  assert.equal((await app.inject({url:'/api/v1/auth/session',headers:{cookie}})).statusCode,200);
  const draft = { id: 'owned', creator: wallet.address.toLowerCase(), title:'Private draft', markets: [], status:'DRAFT', withdrawn:false };
  assert.equal(await store.saveDraft(draft),true);
  assert.equal(await store.saveDraft({...draft, creator: Wallet.createRandom().address.toLowerCase()}),false);
  assert.equal((await store.listDrafts(wallet.address)).length,1);
  assert.deepEqual((await app.inject('/api/v1/sessions')).json().sessions,[]);
  await pool.query("INSERT INTO proofcast_worker_heartbeats VALUES('test-worker',now())");
  await pool.query("INSERT INTO proofcast_worker_state(worker_id,chain_id,block_number,block_hash,indexer_ok) VALUES('test-worker',50312,10,'hash',false)");
  assert.equal((await store.workerHealth()).worker,false);
  await pool.query("UPDATE proofcast_worker_state SET indexer_ok=true");
  assert.equal((await store.workerHealth()).worker,true);
  const status = (await app.inject('/api/v1/indexer/status')).json();
  assert.equal(status.healthy, true);
  await pool.query("UPDATE proofcast_worker_state SET observed_at=now()-interval '31 seconds'");
  assert.equal((await store.workerHealth()).worker,false);
  assert.equal((await app.inject('/api/v1/indexer/status')).json().healthy, false);
  await pool.query("UPDATE proofcast_auth_sessions SET expires_at=now()-interval '1 second'");
  assert.equal((await app.inject({url:'/api/v1/auth/session',headers:{cookie}})).statusCode,401);
  const logout=await app.inject({method:'DELETE',url:'/api/v1/auth/session',headers:{cookie}});
  assert.match(logout.headers['set-cookie'],/Max-Age=0/);
});
