import fs from 'node:fs';
import path from 'node:path';
import { ethers } from 'ethers';

const RPC = process.env.SOMNIA_RPC_URL ?? 'https://dream-rpc.somnia.network';
const configPath = path.resolve('config/shannon.json');
const config = JSON.parse(fs.readFileSync(configPath, 'utf8'));
const key = process.env.PROOFCAST_DEPLOYER_PRIVATE_KEY ?? process.env.DEPLOYER_PRIVATE_KEY;
if (!key) throw new Error('DEPLOYER_PRIVATE_KEY_REQUIRED');
if (process.env.DEPLOY_LIVE !== '1') throw new Error('DEPLOY_LIVE_1_REQUIRED');
const provider = new ethers.JsonRpcProvider(RPC, 50312, { name: 'somnia-shannon', chainId: 50312 });
const network = await provider.getNetwork();
if (network.chainId !== 50312n) throw new Error(`WRONG_CHAIN_${network.chainId}`);
const signer = new ethers.Wallet(key, provider);
const deployer = await signer.getAddress();
const balance = await provider.getBalance(deployer);
if (balance === 0n) throw new Error('DEPLOYER_HAS_NO_STT');
const artifact = name => JSON.parse(fs.readFileSync(path.resolve(`artifacts/${name}.json`), 'utf8'));
const deployed = {};
const deploy = async (name, args) => {
  const a = artifact(name);
  const c = await new ethers.ContractFactory(a.abi, a.evm.bytecode.object, signer).deploy(...args);
  await c.waitForDeployment();
  const receipt = await c.deploymentTransaction().wait();
  deployed[name] = { address: await c.getAddress(), txHash: receipt.hash, block: receipt.blockNumber };
  return c;
};
const marketId = config.dreamdex.marketId;
const catalog = await deploy('ShannonDreamDexCatalog', [marketId, Number(config.dreamdex.nonce), config.dreamdex.pool, config.dreamdex.module, 1788739200, Number(config.dreamdex.expiry)]);
const adapter = await deploy('ProofCastDreamDexAdapter', []);
const registry = await deploy('ProofCastRegistry', [catalog]);
const executor = await deploy('ProofCastExecutor', [await registry.getAddress(), await adapter.getAddress()]);
const factory = await deploy('ProofCastFactory', [await registry.getAddress(), await executor.getAddress(), await adapter.getAddress()]);
const adapterTx = await (await adapter.setFactory(await factory.getAddress())).wait();
const executorTx = await (await executor.setFactory(await factory.getAddress())).wait();
deployed.linking = { adapterSetFactory: adapterTx.hash, executorSetFactory: executorTx.hash };
const next = { ...config, proofcast: { ...config.proofcast, catalog: deployed.ShannonDreamDexCatalog.address, registry: deployed.ProofCastRegistry.address, factory: deployed.ProofCastFactory.address, executor: deployed.ProofCastExecutor.address, adapter: deployed.ProofCastDreamDexAdapter.address }, deployments: { ...(config.deployments ?? {}), proofCastV2: { ...deployed, deployer, rpc: RPC, nativeExecutionEnabled: false, nativeRecoveryEnabled: false, status: 'deployed-fail-closed' } } };
fs.writeFileSync(configPath, `${JSON.stringify(next, null, 2)}\n`);
console.log(JSON.stringify({ project: 'proofcast', chainId: 50312, deployer, balance: balance.toString(), ...deployed, nativeExecutionEnabled: false, nativeRecoveryEnabled: false }, null, 2));
